export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
export const UPDATE_PRODUCT_QUANTITY_IN_CART = 'UPDATE_PRODUCT_QUANTITY_IN_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';